### ISSUE TITLE
1.18.2 and Sodium Support

### ISSUE THREAD

**Issue by Obscure2020** [fl0gic/smooth-chunks#9]
I'm aware that there's already an issue opened about 1.18 support, but I think you need another reminder.

Seriously dude, if there's ever gonna be a 1.18.2 smooth chunk animator, we need you to step up and update your mod. There's literally no other Fabric mod that does this, and the only other mod out there that supports modern versions is a Forge mod.

And at the same time, now is the time to include Sodium compatibility with your mod. Due to the widespread chip shortage under which we now suffer, many of us are stuck playing Minecraft on low-power, low-spec computers. Or at least, that's what _I'm_ stuck with. My computer's graphics card is so low-end and my CPU is so low-clock that the only way I can get _anything_ over 20 FPS is by using Sodium _and_ Entity Culling _and_ Concurrent Chunk Management Engine _and_ FastChest _and_ FerriteCore _and_ Better Beds _and_ Krypton _and_ Lithium **_and_** Starlight. Thankfully, this cavalcade of mods are all compatible with each other and now have all been updated to 1.18.2, and your mod should be too. Nowadays, compatibility is a _must-have,_ not an option. Incompatibility isn't a nuisance, it's **_unforgivable_**.

**Comment by BlazingTide** [comment]
Do it yourself.

**Comment by vrgtics** [comment]
> Do it yourself.

hahaha Funny bro

**Comment by RaptaG** [comment]
@Obscure2020 I COMPLETELY AGREE with this idea what you said is FACTS and it's about time for 1.18.2 & Sodium support

(Also sorry if I hyped you I assume you're waiting for response but I felt like I had to say that I completely support and agree with this idea)

**Comment by gautamknambiar** [comment]
@RaptaG @Obscure2020 Reminder to be kind and empathetic to others, especially when the product you're using is open source and free. They're taking their time to create with no monetary benefit, and I feel like demanding something of a creator when you're not paying for their product can make you come off as a bit entitled. Anyways, have a nice day!

**Comment by Fefedu973** [comment]
Pls update

**Comment by TopchetoEU** [comment]
I'm willing to take up the task of forking this and doing my best to port it over to 1.18. Not too sure about the sodium compatibility thou, I've never worked with Sodium

**Comment by RaptaG** [comment]
> I'm willing to take up the task of forking this and doing my best to port it over to 1.18. Not too sure about the sodium compatibility thou, I've never worked with Sodium


Wow, this would be amazing!

**Comment by vrgtics** [comment]
I just finished about upgraded Gradle to now 1.18.2 compatibility, so then I thanks to nobody later to fix.. 
that **54 error just pop out on my VSCode Problem Tab** :') after Gradle updating. Gook Luck for fixing, 
wish you all the best. *If the following link I send not work at all, I will planning upload on Mediafire

_**myman Please just give me More a Couple of Decades to learn how Java language work til I 23ish years old. _*I better hope_
I really cannot touch any single word in those '.java' files NOW, I really want to BET to understand of HOW I AM, I'm Just Saying....**_

https://drive.google.com/file/d/16y6kxPuG9SHgIsC3UHmkOdox3tte4CqI/view?usp=sharing

**Comment by RaptaG** [comment]
> I just finished about upgraded Gradle to now 1.18.2 compatibility, so then I thanks to nobody later to fix.. that **54 error just pop out on my VSCode Problem Tab** :') after Gradle updating. Gook Luck for fixing, wish you all the best. *If the following link I send not work at all, I will planning upload on Mediafire
> 
> _**myman Please just give me More a Couple of Decades to learn how Java language work til I 23ish years old. _*I better hope_ I really cannot touch any single word in those '.java' files NOW, I really want to BET to understand of HOW I AM, I'm Just Saying....**_
> 
> https://drive.google.com/file/d/16y6kxPuG9SHgIsC3UHmkOdox3tte4CqI/view?usp=sharing

I suppose that there's no Sodium support, right?

**Comment by vrgtics** [comment]
yeah you suppose right. 
Edit: --------
What I am doing is only updating Gradle/Gradlew Package to 7.3.1/Fabric Loom 0.11-snapshot
mod's ready to build for 1.18.2- **(IF `src/main java cc.flogi.dev.smoothchunks` folder HAS NO 
MORE ERROR COMING..)** that what Gradle suppose to do, I guess. 

_*_ **I'm Not look for Sodium support FIRST**, 

but FIRST look for there's errors need to be Fix.

IMPORTANT: ALSO I think **those error MIGHT ARE _cadenkriese_ new feature,** 
I giving you to aware **JUST Make Sure IF you REALLY Need To 
Delete Some Codes THAT ARE NOT AFFECT TO OTHER.**

**Comment by florianreuth** [comment]
I'm currently in the process of porting the mod for my utility mod to 1.19 with Sodium support, if the port is reasonably good I will release a new Smooth Chunks mod.

**Comment by Fefedu973** [comment]
> I'm currently in the process of porting the mod for my utility mod to 1.19 with Sodium support, if the port is reasonably good I will release a new Smooth Chunks mod.

Let's go !!!! please do it also for 1.18.2 please

**Comment by Fefedu973** [comment]
> I'm currently in the process of porting the mod for my utility mod to 1.19 with Sodium support, if the port is reasonably good I will release a new Smooth Chunks mod.

Let's go !!!! please do it also for 1.18.2 please

**Comment by Fefedu973** [comment]
> I'm currently in the process of porting the mod for my utility mod to 1.19 with Sodium support, if the port is reasonably good I will release a new Smooth Chunks mod.
What is the name of your mod? Any idea when it will be out? Will it be 1.18.2 compatible? Thanks

**Comment by Fefedu973** [comment]
> I'm currently in the process of porting the mod for my utility mod to 1.19 with Sodium support, if the port is reasonably good I will release a new Smooth Chunks mod.
What is the name of your mod? Any idea when it will be out? Will it be 1.18.2 compatible? Thanks

**Comment by cadenkriese** [comment]
I considered returning to this mod; this issue killed any motivation I had.

I don't want to rant. I want to say to @Obscure2020 @RaptaG and all the demanding comments on CurseForge that open-source developers do not owe you anything. The Minecraft community, in particular, seems to struggle with this. Nearly all the devs who publish their hard work on GitHub do it for free. It's a shame when they get lambasted because they didn't meet someone's expectations.

And above all that, be kind and empathetic. Try to make the Minecraft community a better place by remembering it's a community for everyone, and nobody is entitled to anything.

Fortunately for you, another talented developer has picked this up and implemented it in a much better way than I had. I can only hope they face less entitled comments than I have.

edit to add: I'm not playing the victim here; I'm not personally hurt by these comments like much less fortunate creators in this space have been. I simply don't want to go out of my way to work on something that rewards entitled and demanding people.
